/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_com_umedia_smartcard_service_PCSCService */

#ifndef _Included_tw_com_umedia_smartcard_service_PCSCService
#define _Included_tw_com_umedia_smartcard_service_PCSCService

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    EstablishContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_EstablishContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    ReleaseContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_ReleaseContext
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    IsValidContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_IsValidContext
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Connect
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Connect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Reconnect
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Reconnect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Disconnect
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Disconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    BeginTransaction
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_BeginTransaction
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    EndTransaction
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_EndTransaction
  (JNIEnv *, jobject, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Status
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Status
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    GetStatusChange
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_GetStatusChange
  (JNIEnv *, jobject, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Control
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Control
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Transmit
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Transmit
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    ListReaderGroups
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_ListReaderGroups
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    ListReaders
 * Signature: ()[Ljava/lang/String
 */
JNIEXPORT jobjectArray JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_ListReaders
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    FreeMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_FreeMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    Cancel
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_Cancel
  (JNIEnv *, jobject);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    GetAttrib
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_GetAttrib
  (JNIEnv *, jobject, jlong);

/*
 * Class:     tw_com_umedia_smartcard_service_PCSCService
 * Method:    SetAttrib
 * Signature: (I[B)J
 */
JNIEXPORT jlong JNICALL Java_tw_com_umedia_smartcard_service_PCSCService_SetAttrib
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif

#endif
